# Start Polkit
{% if salt['file.file_exists']('/usr/libexec/polkit-gnome-authentication-agent-1') %}
exec-once = /usr/libexec/polkit-gnome-authentication-agent-1
{% elif salt['file.file_exists']('/usr/libexec/xfce-polkit') %}
exec-once= /usr/libexec/xfce-polkit
{% endif %}

# Load Dunst Notification Manager
exec-once = dunst

exec-once = pkill waybar;sleep 1;waybar

exec = swaybg -m fill -i /home/deckard/.wallpaper/wallhaven-blackhole.png
