# Start Polkit
{% if salt['file.file_exists']('/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1') %}
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
{% elif salt['file.file_exists']('/usr/libexec/xfce-polkit') %}
exec-once= /usr/libexec/xfce-polkit
{% endif %}

# Load Dunst Notification Manager
exec-once = dunst

#exec-once = pkill waybar;sleep 1;waybar
exec-once = pkill ashell;sleep1;ashell

exec-once = hypridle

exec = swaybg -m fill -i /home/deckard/.wallpaper/wallhaven-blackhole.png
