

#-----------------
# Monitor
#-----------------
source = ~/.config/hypr/conf/monitors.conf


#----------------
# Environment
#----------------
source = ~/.config/hypr/conf/environment.conf


#----------------
# Keybinds
#----------------
source = ~/.config/hypr/conf/keybinds.conf

#----------------
# Autostart
#----------------
source = ~/.config/hypr/conf/autostart.conf

#----------------
# Hyprlock
#----------------
#source = ~/.config/hypr/conf/hyprlock.conf